### ISSUE TITLE
Record CREATED on the SERVER and then UPDATED on the SERVER - Error

### ISSUE THREAD

**Issue by luigi37** [abeauseigle/TodoApp#7]
It seems there is a conditions which triggers an error:

1- create record on the server: "id" will be null. Ok
2- sync on the app: the record gets created in the app. Ok
3- modify the record on the server (update last_sync_date). Ok
4- sync app. ERROR:

     Error : could not execute statement (20 datatype mismatch) (Code 1) Line 660 _errorHandler, Transaction.sql = undefined 

Which I think comes from the query:

    _executeSql Line 634: UPDATE mytable SET "id" = "null", "Model" = "xxx123", "BDBid" = "", "last_sync_date" = "2014-11-05 20:59:19", "last_sync" = "1415217565917" WHERE Gear_ID = "1001512" with param:  webSqlSync.js:635

This happen with both 

     SET "id" = "null"
and

     SET "id" = ""

The error seems logical as "id" on the app is an integer (actually unique key). In principle the "id" should NOT be updated on the client once assigned.

**Comment by abeauseigle** [comment]
See the new code in https://github.com/abeauseigle/TodoApp2
It gives an improved websqlsync.js and a really better webSql app.
